version: "3.7"

services:
  react-app:
    container_name: frontend-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - ".:/app"
    ports:
      - "3000:3000"

    command: >
      bash -c "npm run start"
